In [1]:
#Importing packages
import pandas as pd
import numpy as np

<ipython-input-1-75f9e765d065>:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
data = pd.read_csv("orders.csv")
df = pd.DataFrame(data)
df

OrderID  CustomerID  Amount   OrderDate
0      101         1.0  250.50  2024-12-20
1      102         2.0  120.00  2024-12-21
2      103         3.0  320.00  2024-12-22
3      104         4.0     NaN  2024-12-23
4      105         NaN  150.75  2024-12-24

In [4]:
#Filling missing values
df["CustomerID"] = df["CustomerID"].bfill()
df

OrderID  CustomerID  Amount   OrderDate
0      101         1.0  250.50  2024-12-20
1      102         2.0  120.00  2024-12-21
2      103         3.0  320.00  2024-12-22
3      104         4.0     NaN  2024-12-23
4      105         NaN  150.75  2024-12-24

In [5]:
new_df=df.interpolate()
new_df

<ipython-input-5-dfbaf556cf83>:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df=df.interpolate()


OrderID  CustomerID   Amount   OrderDate
0      101         1.0  250.500  2024-12-20
1      102         2.0  120.000  2024-12-21
2      103         3.0  320.000  2024-12-22
3      104         4.0  235.375  2024-12-23
4      105         4.0  150.750  2024-12-24

In [6]:
df.describe()

OrderID  CustomerID      Amount
count    5.000000    4.000000    4.000000
mean   103.000000    2.500000  210.312500
std      1.581139    1.290994   91.924646
min    101.000000    1.000000  120.000000
25%    102.000000    1.750000  143.062500
50%    103.000000    2.500000  200.625000
75%    104.000000    3.250000  267.875000
max    105.000000    4.000000  320.000000

In [7]:
df["CustomerID"].value_counts() #Counts unique values in the column CustomerID

CustomerID
1.0    1
2.0    1
3.0    1
4.0    1
Name: count, dtype: int64

In [8]:
orders_df =df[["OrderID","Amount"]]
orders_df

OrderID  Amount
0      101  250.50
1      102  120.00
2      103  320.00
3      104     NaN
4      105  150.75

In [9]:
orders_df["Amount"]=orders_df["Amount"].apply(lambda x : x + 50)
orders_df

<ipython-input-9-05e37c86839f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_df["Amount"]=orders_df["Amount"].apply(lambda x : x + 50)


OrderID  Amount
0      101  300.50
1      102  170.00
2      103  370.00
3      104     NaN
4      105  200.75

In [10]:
arr = orders_df["Amount"].to_numpy()
arr

array([300.5 , 170.  , 370.  ,    nan, 200.75])

In [11]:
arr.dtype

dtype('float64')

In [12]:
np.vstack(arr)
# Creates a vertical stack

array([[300.5 ],
       [170.  ],
       [370.  ],
       [   nan],
       [200.75]])

In [13]:
np.hstack(arr) #creates a horizontal stack

array([300.5 , 170.  , 370.  ,    nan, 200.75])

In [14]:
np.sort(arr)

array([170.  , 200.75, 300.5 , 370.  ,    nan])

In [15]:
np.unique(arr)

array([170.  , 200.75, 300.5 , 370.  ,    nan])

In [16]:
arr[np.where(arr < 200)]

array([170.])

In [17]:
#Max and min elements
arr[np.argmax(arr)]

nan

In [18]:
arr[np.argmin(arr)]

nan